### ISSUE TITLE
Error in dowloading big file

### ISSUE THREAD

**Issue by stdedos** [konklone/json#135]
Sublime reports 5.060.081 chars-json.

Conversion was successfull (as far as "general feeling" and "total result [of the json-producing programm]/ total rows [of your program]"), although a little sluggish.

However downloading it didn't prompt for a name - "download" was the prompt, and the download failed, so I had to copy by hand

I am aware of "Extremely large files may cause trouble — the conversion is done inside your browser.", I just thought I should report. I can provide the data used privately if necessary.

**Comment by degaray** [comment]
I have the same issue. I uploaded a 430 row and the conversion was ok. However, the download was not ok. I have normally done so successfully, it was something done recently I guess.

**Comment by konklone** [comment]
Nothing has changed recently.... no commits to the project since July 2016. It's possible browser behavior has changed, and you might consider trying alternate browsers and seeing if they work.

The download link works by using `data:` URIs, and browsers do impose limits on what can be placed inside those. They could be lowering in one or more browsers over time.

**Comment by degaray** [comment]
That did work. I was using Chrome and I tried with Firefox and it worked. Thanks!
