### ISSUE TITLE
Error parsing some specific JSON: It's the response from Google QPX Express API

### ISSUE THREAD

**Issue by yashvardhannanavati** [konklone/json#141]
I'm having an issue converting this JSON:

`[removed]`

**Comment by konklone** [comment]
This looks like a Python dict, and not JSON. We do try to catch single quoted keys/values and change them to double quotes, but I see other issues here (such as `True` instead of `true` for boolean values).

You should get this data into proper JSON form first, and then try again. I'm removing the data from the issue body above since it's large and unneeded, but here's a snippet to reference the issues I was talking about:

> {'trips': {'tripOption': [{'saleTotal': 'USD286.20', 'id': '3NmVBpjS7jIMEbqVYLfRRP002', 'slice': [{'duration': 380, 'segment': [{'kind': 'qpxexpress#segmentInfo', 'duration': 380, 'bookingCode': 'S', 'leg': [{'aircraft': '777', 'mileage': 2697, 'originTerminal': 'B', 'onTimePerformance': 30, 'origin': 'BOS', 'duration': 380, 'destination': 'SFO', 'id': 'L+71XoaWr+d5ytI9', 'kind': 'qpxexpress#legInfo', 'secure': True, '
