### ISSUE TITLE
Request to add a feature to Parse JSON Data from a URL 

### ISSUE THREAD

**Issue by miststudent2011** [konklone/json#187]
Hi, is there a way to parse data from the url directly instead of copying json data or uploading json file 

Url for Json Data for reference.

https://labs.data.gov/dashboard/datagov/convert?orgs=dot-gov

**Comment by konklone** [comment]
I appreciate the request, but I don't think it's right for this application.

There's some discussion here of this: https://github.com/konklone/json/issues/5

But the short of it is that to do this with a client-side only solution would necessitate that the data being fetched has CORS enabled, which is not going to be very common. And to do this server-side would be a total architecture shift with a lot more complexity, so that is unlikely.

**Comment by miststudent2011** [comment]
I think I found a way to perform the task with ajax call

I modified your code in my local and was able to achieve the functionality.

Here is the gist for the modification

https://gist.github.com/miststudent2011/ef7dcc1780202dd244b07ab80b215de3

**Comment by konklone** [comment]
I think this will only work for JSON URLs that have CORS enabled, not in the general case.
