### ISSUE TITLE
UTF-8 Error

### ISSUE THREAD

**Issue by gogl92** [konklone/json#192]
Problem converting JSON's with other languages special characters.

From
"Adquisición de mercancias"
To
"AdquisiciÃ³n de   mercancias"
--

**Comment by konklone** [comment]
Can you show me an example by creating a permalink? Generally this has worked okay, and the issue has been in user CSV viewers. But I'm happy to look at a specific case.

**Comment by gogl92** [comment]
Yes I think the problem is the CSV because in the table shown online it is ok.
[permalink](https://konklone.io/json/?id=b14e989c1d709f3fe1bac0737c0ca9b3)

**Comment by konklone** [comment]
I think the problem is in your CSV viewer. The CSV also looks okay, when I open it in my CSV viewer (LibreOffice):

![screenshot from 2017-12-05 22-51-08](https://user-images.githubusercontent.com/4592/33643703-d85caa58-da0e-11e7-9773-fba49ff84210.png)

And when I look at it in text via the terminal, I see at the top:

```
key,name,use
G01,Adquisición de mercancias,ambos
G02,"Devoluciones, descuentos o bonificaciones",ambos
```

If you can pin it down to something specific, let me know, but I think the issue is likely in your viewing environment.

**Comment by gogl92** [comment]
Thank you, yes the problem was the viewer.
