### ISSUE TITLE
CSV output causes problems for some apps

### ISSUE THREAD

**Issue by konklone** [konklone/json#21]
The output we produce for https://www.opm.gov/data.json (http://konklone.io/json/?id=9415277) is screwing up everyone except LibreOffice (gnumeric, Excel), because some fields have commas, even though it appears totally valid. 

At least determine conclusively whether the output is faulty, or if there's anything the app can do in its output to improve interoperability.

**Comment by ajschumacher** [comment]
It looks like the problem is that not all the internal quotes are getting escaped (where here I mean it in the goofy RFC 4180 double-quote-is-the-escape-for-a-quote-sense). Take a look at line ten of the CSV in what you linked to:

FedScope Accessions Cubes,"This raw data set provides the actual number of personnel actions (""Transfer-Ins" and "New Hires") ...

Those quotes were \" escaped in the JSON, but only the first one is getting double-quote escaped in here. Is some regex not /g?

**Comment by konklone** [comment]
Good eye, @ajschumacher, you are right. And making matters worse, this version of [jquery-csv](https://code.google.com/p/jquery-csv/) is unsupported - it's 0.70, and 0.71 actually removes the `fromObjects` method entirely.

The real solution is to replace jquery-csv with our own flat-object-to-csv output method (which won't need all the fanciness of jquery-csv). 

In the meantime, I've hotfixed the problem in jquery-csv in https://github.com/konklone/json/commit/4563d9c9e2b7f6f8d556a1b39b0dcee4985eab01, and http://konklone.io/json/?id=9415277 should now parse OPM's `/data.json` file correctly.

Thanks @ajschumacher! And to @philipashlock, who originally reported this.
