### ISSUE TITLE
What is the issue with this json file

### ISSUE THREAD

**Issue by dudestc** [konklone/json#222]
{"items": [{"position": {"timestamp": "2018-09-19T17:22:22.000Z", "altitude": null, "longitude": -0.436744, "latitude": 51.396649, "speed": 11.33333333333333
4, "heading": 78.0}, "platformDriveSessionIdentifier": "AFA76AA292704D49A7C2D1977CC750A9", "platformVehicleIdentifier": "1019C2A35E83B2FCE6E550DAC0B58334"}]}

**Comment by mzmcbride** [comment]
What's pasted in this GitHub issue is not valid JSON and that may be the issue. There's an errant line break after `.33333333333333` and before `4,` that is making the JSON invalid. When I remove that line break and use the otherwise same text from this issue, I'm able to successfully use the tool at <https://konklone.io/json/> to render an HTML table. The raw data is:

```
position/timestamp,position/altitude,position/longitude,position/latitude,position/speed,position/heading,platformDriveSessionIdentifier,platformVehicleIdentifier
2018-09-19T17:22:22.000Z,,-0.436744,51.396649,11.333333333333334,78,AFA76AA292704D49A7C2D1977CC750A9,1019C2A35E83B2FCE6E550DAC0B58334
```
