### ISSUE TITLE
Port request: Make this awesome script available as a Google App Script that takes in values from cells and urls

### ISSUE THREAD

**Issue by GOESPROTOCALL** [konklone/json#236]
I've came across a few solutions to parse JSON data in Google sheets but none provides a result presentation as neat as what I can get in your tool. Sadly I can't deal with having to copy paste data into your page all the time to get thousands of datasets converted to table and copy paste back into the sheets. 

If would be fantastic if you could have some sort of integration with google sheets? The most straight forward solution would be GAS I guess. 

Here's an example of how it could work, though I didn't like it as much as I like yours.
https://medium.com/@paulgambill/how-to-import-json-data-into-google-spreadsheets-in-less-than-5-minutes-a3fede1a014a

**Comment by konklone** [comment]
I appreciate that this would be helpful, but it's not in the cards for this service. My JSON to CSV converter has one main advantage for users: completely private (no data is sent to my or GitHub's servers), and one main advantage for me the dev: no servers to run. 

Because of those benefits, there's no server, and nothing for Google Sheets to submit JSON data to. This is unlikely to change, so you'll likely have to use other methods.

One thing that is a bit more possible would be a standalone JS library, and some supported instructions to e.g. paste something into Google Apps Script that would do the conversion there. There's no reason GAS couldn't do the conversion inline - it's just JavaScript.

**Comment by GOESPROTOCALL** [comment]
I do appreciate that your tool is complete private as well, but it has it's limitations (mostly on the user's end due to slower computers) when dealing with huge datasets. Making this available as a GAS script will help to leverage on google's resources if people chooses to, if they dont mind having the data leaked.

As I don't have a good understanding of how your converter works, and it seems like you're pretty good with JS, wouldn't you do us a a favor and do the translation to JS please?
