### ISSUE TITLE
BUG with array

### ISSUE THREAD

**Issue by Edo78** [konklone/json#32]
I just try to convert this JSON
{"a":"ciao","b":[0,3,5]}

and I get this CSV

0
3
5

(no column "a" and no title for the column "b")
http://konklone.io/json/?id=11152089

**Comment by konklone** [comment]
Yep - this is because the parser has a heuristic to try to "detect the array", so that it can handle common JSON formats where the primary record is an element in an array that is a subfield of the main object, e.g.:

``` json
{
  "results": [ ... ]
}
```

The above is so common, that the heuristic optimizes for that. It's not great - there should be a way for advanced users to override that (and for that override to be carried along in the permalink). 

This is discussed further in #4, so I'm going to close this in favor of discussing it in that ticket.
