### ISSUE TITLE
Support nested JSON

### ISSUE THREAD

**Issue by daumann** [konklone/json#34]
Please use the JSON at the below link to test. Here, looking at the result, group should be a column and not a row - also most columns should be rows:

http://konklone.io/json/?id=c2a83441af8b9421476e

**Comment by konklone** [comment]
I moved the JSON into the converter and created a permalink, to make the ticket more readable.

I'm honestly not sure how this should be converted to a CSV in an automated way, except with a JS override as in #31. But if you want to provide some ideas for an algorithm, I'm open to them.

**Comment by skibulk** [comment]
Maybe in the case of nested arrays and objects, each level could become a separate CSV file. Then the top level csv could have some kind of maker or link to the child CSVs. The levels could even be stacked in one CSV file using links.

**Comment by lsinger** [comment]
If there was a way to create merged cells and rows in CSV, you could use nested tables that reflect the structure of the JSON, e.g. like in the example below (movies playing at different movie theaters and their playing times). Maybe instead of merging cells one could simply use empty cells to reflect that structure? 

![screen shot 2014-11-27 at 10 53 32 am](https://cloud.githubusercontent.com/assets/23619/5215053/aca7504a-7623-11e4-94e0-1cb27070178b.png)

**Comment by konklone** [comment]
Closing as non-actionable. It's just too complicated for this tool.
