### ISSUE TITLE
Support big files

### ISSUE THREAD

**Issue by tmcw** [konklone/json#35]
Just a thought, but this would be possible with [filereader-stream](https://github.com/maxogden/filereader-stream), [binary-csv](https://github.com/maxogden/binary-csv), and [filesaver](https://github.com/eligrey/FileSaver.js), though with [semi-limited browser support](http://caniuse.com/#search=filereader).

**Comment by konklone** [comment]
That browser support is good enough for me!

While those would handle a streaming reading for the file, and a streaming generation of the resulting CSV, I think it's missing two things: a streaming JSON parser, and streaming file download.

@maxogden and I discussed streaming JSON parsing in #13, and he pointed me to [Oboe.js](http://oboejs.com/), which certainly projects reliability in its marketing. So maybe that would fill that gap.

But I think in order to do streaming downloads and avoid ever holding the big file in memory, the [Streams API](https://dvcs.w3.org/hg/streams-api/raw-file/tip/Overview.htm) would need to be supported. Without it, FileSaver.js still holds the whole file in memory. Am I wrong about that?

It seems like every single part of the process would need to support streaming to make this worthwhile. :/

**Comment by tmcw** [comment]
Sorry, yeah - as far as I can see, we can't support streaming on every level, so this isn't possible.

**Comment by konklone** [comment]
@tmcw OK, jumping two years in the future -- are you sure? I implemented real streaming at the FileReader level in https://bit.voyage and it worked. The bottleneck there is the S3 Multipart Upload chunk size limit, but that wouldn't be a factor here.
