### ISSUE TITLE
Blue window via Chrome = 'Oh Snap' when attempting to download data to CSV file.

### ISSUE THREAD

**Issue by Malibu2105** [konklone/json#59]
Hello Github,
Hope all is well...
We receive a Blue window via Chrome = 'Oh Snap' when attempting to download data to CSV file.
Json has not been working for the last of couple of days. 
This morning I was able to download and save two items without issue. 
The 3rd attempt to save a csv file =  Blue window via Chrome = 'Oh Snap'.
Please advise and resolve as soon as possible.
Thank your for your help.
Chris Brandes

**Comment by konklone** [comment]
This isn't enough information to be actionable. If you can provide some specific input data that _consistently_ causes a crash, and the specific version of Chrome and which OS you're using it on, please re-open the issue. Otherwise, I have to assume the problem is specific to your system, not the website.
